### ISSUE TITLE
Journal-Entries produce empty parenthesis with labelyear=false

### ISSUE THREAD

**Issue by ypsilonkah** [jspitz/biblatex-publist#13] opened 2018-08-29 18:55 UTC
Hi,
publist produces a strange behavior with the option `labelyear=false`: an empty pair of parenthesis is added.

> 2017. »example journal article« In: example journal, vol(no) **( )**, S. 94–96.

Setting `labelyear=true` removes the parenthesis.

**Comment by jspitz** [comment] 2018-08-30 07:47
Cannot reproduce. Please provide a minimal example file.

**Comment by ypsilonkah** [comment] 2018-08-30 12:00
Cf for a MWE. If the value for `labelyear` or `labeldateparts` is set to false, parenthesis are added. I updated my code according to your hint that `labelyear` is deprecated  (#12). However, the behaviour still remains.

The error occurs on a fresh texlive 2018 install (setup yesterday). 

```
\documentclass[]{article}
\usepackage{filecontents}
\usepackage[bibstyle=publist,
 			backend=biber,
 			labledateparts=false]{biblatex}
\plauthorname[Jane]{Doe}
\addbibresource{\jobname.bib}
 
\begin{filecontents}{\jobname.bib}
 	@article{Doe.2016,
 		author = {Doe, Jane and Due, John},
 		year = {2016},
 		title = {Example title},
 		pages = {1--13},
 		pagination = {page},
 		volume = {4},
 		number = {1},
 		journal = {Topnotch Studies}
 	}
\end{filecontents}
 
\begin{document}
\nocite{Doe.2016}
\printbibliography
\end{document}
```

[publist.pdf](https://github.com/jspitz/biblatex-publist/files/2336032/publist.pdf)
[publist.txt](https://github.com/jspitz/biblatex-publist/files/2336033/publist.txt)

**Comment by jspitz** [comment] 2018-08-31 08:10
I suspect this is an upstream problem in biblatex. See https://github.com/plk/biblatex/issues/793

**Comment by jspitz** [comment] 2018-09-01 12:08
I committed a workaround which fixes this with the standard base style.

**Closed as completed** 2018-09-01 12:07 UTC

**Comment by ypsilonkah** [comment] 2018-09-01 12:39
Thank you for your effort.
