### ISSUE TITLE
No comma after initial followed by a period (.)

### ISSUE THREAD

**Issue by montdor** [jspitz/biblatex-publist#17] opened 2018-09-29 00:13 UTC
I'm unsure if this issue is related to the other issue I opened, so I decided to open them separately.
With the same setup as the previous (i.e. any initial followed by a period), there is no longer a comma following the name.
E.g. if John J. Doe, Jane D. Smith, and George R. Martin wrote an article, it shows up as: Doe, John J. Smith, Jane D. And Martin, George R. (the And capitalization is the same as the last issue).

**Comment by jspitz** [comment] 2018-09-29 08:58
duplicate of #16.

**Closed as completed by jspitz** 2018-09-29 08:58 UTC
