### ISSUE TITLE
Unexpected Space After Parenthesis in Custom \plyearhl Command

### ISSUE THREAD

**Issue by SongshGeo** [jspitz/biblatex-publist#56] opened 2024-08-19 09:59 UTC
Hello Jürgen,

Sorry to bother you again by opening another issue. After using your package and following your advice on adding author annotations, I finally completed a beautifully formatted publication list. Thank you so much for your help!

However, a small imperfection has led me to open this issue (maybe I'm a bit of a perfectionist).

The place where I need to submit my publication list requires a format where the year is in parentheses and follows directly after the author list. Therefore, I removed the month and day fields and customized the `\plyearhl` command to add parentheses around the year:

```LaTeX
% highlight year with parentheses
\renewcommand*\plyearhl[1]{%
    (#1)%
}
% ignore month and day
\AtEveryBibitem{
  \clearfield{month}
  \clearfield{day}
}
```

However, after doing this, a small space appears after the opening parenthesis that I can't seem to remove. I tried using `\xspace` and `\unskip`, but neither solved the issue.

Could this be something that can be improved?

![CleanShot2024-08-19at17.50.13@2x](https://songshgeo-picgo-1302043007.cos.ap-beijing.myqcloud.com/uPic/CleanShot%202024-08-19%20at%2017.50.13@2x.png)

Thank you again for your excellent work and assistance!

**Comment by jspitz** [comment] 2024-08-19 11:39
Easiest solution:
```tex
\usepackage{xpatch}
\xpatchbibmacro{bpl:date:makedate}{\iffieldundef{year}}{\unspace\iffieldundef{year}}
```

**Comment by SongshGeo** [comment] 2024-08-19 15:31
> Easiest solution:
> 
> ```
> \usepackage{xpatch}
> \xpatchbibmacro{bpl:date:makedate}{\iffieldundef{year}}{\unspace\iffieldundef{year}}
> ```

Great, it does work! Thanks a lot.

**Comment by jspitz** [comment] 2024-08-19 15:58
Good. Closing, as this is not a bug.

**Closed as completed by jspitz** 2024-08-19 15:58 UTC
